### ISSUE TITLE
Redesign AbstractMotor

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/HardwareRepository#137]
Use MotorMockup and MicrodiffMotorMockup for testing. See PR #138 for details.

**Comment by rhfogh** [comment]
I happened to notice that mouse scroll (in mock mode, with a MotorMockup for the Omega motor) triggered the  following error
 
  File "/MXCuBE/mxcube/HardwareRepository/HardwareObjects/Qt4_GraphicsManager.py", line 852, in mouse_wheel_scrolled
	self.diffractometer_hwobj.move_omega_relative(- self.omega_move_delta)
  File "/MXCuBE/mxcube/HardwareRepository/HardwareObjects/DiffractometerMockup.py", line 416, in move_omega_relative
	self.motor_hwobj_dict['phi'].syncMoveRelative(relative_angle, 5)
  File "/MXCuBE/mxcube/HardwareRepository/BaseHardwareObjects.py", line 345, in getattr
	raise AttributeError(attr)
AttributeError: syncMoveRelative

It looks like syncMove and syncMoveRelative are used in a lot of places (including GenericDiffractometer, DiffractometerMockup, and sample_centring), and defined in a  lot of motors, but are not defined in AbstractMotor or MotorMockup. How should this be handled?

**Comment by IvarsKarpics** [comment]
Hi @rhfogh ,

Thanks for raising the issue. My suggestion would be to add necessary methods with deprecation warning as in #149 . I will prepare a PR on Monday.

Cheers,
Ivars
