### ISSUE TITLE
Refactoring MXCuBE

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/HardwareRepository#139]
Dear all,

I'm creating this issue as we discussed during the last meeting, I will add a short background and aim of the refactoring process bellow. Please correct me if you feel that I'm wrong or that you are missing something.

Cheers,
Marcus

**Comment by marcus-oscarsson** [comment]
Background
==========

The beamline abstraction layer within MXCuBE, today implemented with
HardwareObjects, have evolved during the last years to include an increasing 
number of features. The way in which beamlines are controlled have also 
changed during the same time. The need for the fine grained control that the
HardwareObjects originally was convinced for is decreasing. What was previously
done as a set of operations, for instance motor movements, are today completely
done within certain hardware or handled by the underlying beamline control layer.
Furthermore, each institute also does the concrete implementations in different
ways. This have led to larger and larger quantities of institute specific code.

There have been some efforts to try to decrease the amount of institute specific
code by using a set of abstract base classes to define a API for the most common
HardwareObjects. A solution which, arguably, only solves the problem partially 
since the way that instrument control is done today require institute specific
implementations.

The introduction of new features at a rapid pace without little retrospect and 
refactoring have also led to an architecture that is slightly outdated, 
difficult to understand and maintain. 

The state of the beamline abstraction layer have been discussed during the last 
MXCuBE meetings, in order elevate these issues. 

It was decided that the developers committee will perform a prestudy in order to
find a new architecture that solves these issues. Inspiration could be taken from
the MXCuBE3 application, where a REST API defines a clear separation between UI 
and backend. The new architecture should also have room for institute specific 
implementations which can be easily shared through a set of well defined core
components.

Aim
===

To design a: 

  - More modular architecture that defines a clear API between each
    core component constituting the MXCuBE core.

  - Define a API between the UI and the MXCuBE core (taking inspiration from MXCuBE3)

  - Allowing for institute specific code and the possibility to share that code
    easily when necessary


This work should also include defining the necessary coding standards, documentation 
tools and testing frameworks.

**Comment by marcus-oscarsson** [comment]
A possible design to start the discussions around could be the one bellow. I have for the time being assumed that the the two user interfaces does not share the same API to access the common UI layer. However its completely possible that the Qt application could use the REST API.

![document sans titre](https://user-images.githubusercontent.com/4331447/36379009-48a8a2e0-157d-11e8-8c29-2e74b9ea98d6.png)

The REST API and the Common UI API layer would probably be merged together if there is no Qt specific API. The idea of the COMMON UI API is simply to remove the technical, if any, difficulties to implement the REST API in Qt.

The core components of CORE COMPONENTS remains to be defined, here is a possible list:
 - Login
 - LIMS
 - Processing
 - Beamline
 - Diffractometer
 - Sample Shanger
 - Sample Centring
 - Queue
 - Beamline

Each layer of course needs to further looked at separately, but this could be used as a discussion starter.

**Comment by marcus-oscarsson** [comment]
It seems like some more detail regarding the proposed architecture is needed to be able to continue the work of defining the COMMON UI API. Whether or not we need the REST API and the Qt specific API remains to be seen.

The REST API used by the MXCuBE3 application can be used as a starting point, I've listed them below and attached them in txt format. These routes call underlying python functions which can be shared in a COMMON UI API with the Qt application (if needed). The routes are defined in separate files under the mxcube3/routes directory, the name of the file can be found above the function names. You can easily identify a set of categories such as queue, lims and sample changer. I can imagine that we need to improve the naming or signature of certain functions or even move them from one category to another. 

REST API:
[routes.txt](https://github.com/mxcube/HardwareRepository/files/1789574/routes.txt)

Events/signals:
[signals.txt](https://github.com/mxcube/HardwareRepository/files/1789573/signals.txt)

I hope this is enough to get a discussion started, around the UI API.

**Comment by bourenkov** [comment]
Dear Marcus,

Now,  with an embrio documentation for REST API and a reference to the working code behind it, we can start the discussion. It was not possible without, so thanks for your work!

In order to understand how exactly the new API should solve our problems (mostly with site specificity),  let us look at one simple example:

We have an API:
--------------------------
@mxcube.route("/mxcube/api/v0.1/diffractometer/aperture", methods=['PUT'])
def set_aperture():
    """
    Move the aperture motor.
        :request Content-type: application/json, new position {'diameter': 50}.
            Note: level specified as integer (not 'Diameter 50')
        :statuscode: 200: no error
        :statuscode: 409: error
    """
    params = request.data
    params = json.loads(params)
    new_pos = params['diameter']
    aperture_motor = mxcube.diffractometer.getObjectByRole('aperture')
    logging.getLogger('HWR').info("Changing aperture diameter to: %s" % new_pos)
    aperture_motor.moveToPosition(int(new_pos))

    return Response(status=200)
--------------------

and a slide 23 from Matthias' presentation at Diamond stating that new MxCuBE will be the UI and API (but not the HardwareOjects)

My question is: what "mxcube.diffractometer" is supposed to be?

Thanks again, and best regards
Gleb 
I'll e-mail the question around just those who do not read the github.

**Comment by marcus-oscarsson** [comment]
Hi Gleb,

I'm happy that you have enough information to continue the work. First of all the UI API does not address site specific adaptions more than today without refactoring the core components. mxcube.diffractometer is any  diffractometer HardwareObject, its attached to the mxcube app object when the application is initialized. 

The HardwareObjects used are the ones on branch 2.2 so the same as our Qt3 version of MXCuBE here at ESRF. The XML configuration files are the same across the two applications. 

Marcus

**Comment by mguijarr** [comment]
I think Gleb's question is more: what should be/become `mxcube.diffractometer` in the frame of our proposal.

So, my opinion is that the Hardware Repository should be replaced with an API based on "contracts" between MXCuBE user interface and beamline hardware.

In the specific case of aperture, we can see from the MXCuBE 3 REST API that a possible contract
could be: there is a `set_aperture` request, which receives the diameter of the aperture to set, and
returns ok when it's done. The underlying implementation is site-specific, and can be kept private
at each site.

What has to be defined:
- how the UI communicates with the beamline API ? (in short: do we start with the same API as MXCuBE 3, through http requests ?)
- a refined version of the API contracts, to suit existing User Interfaces (Qt and web)

I hope this makes my proposal more clear.

**Comment by bourenkov** [comment]
Hi Marcus and Mattias,

Yes, that was exactly the question. The answer, i.e. the meaning of the term "Contracts" needs a clarification - I apologize for my ingnorance.  

I am mostly worried about the downstream part of the interface - towards the beamline control. Perhaps, an example (pseudo-)code of an API function connecting to any existing HO could be instructive. 

Concerning how GUI will communicates with the API - I see it less of a conceptual problem at this point. We will probably have more than one interface on that end (as Qt application talking http to itself does not seem too clever to me).

**Comment by rhfogh** [comment]
One form of the contract might be a Python 3 abstract class, with type-annotations and doc strings on the functions. That is just one technology, but it should be about the level of detail you would want. For a hypothetical get_detector_width one would certainly want to know whether it is int or float, and in units of pixels, mm, or m.

**Comment by IvarsKarpics** [comment]
Hi all,

I think the discussion is going to the correct direction and the actual question is "what we mean with API?". The example with `set_aperture` (and it is an easy example) shows that it needs a different representation because code lines:

```
aperture_motor = mxcube.diffractometer.getObjectByRole('aperture')
aperture_motor.moveToPosition(int(new_pos))
```
are site specific and are based on many assumptions:
- diffractometer hwobj has a aperture hwobj.
- aperture hwobj has a method moveToPosition that accepts variable as int.

One solution would be to eliminate the notation of hardware objects and sub categories, like diffractometer and call the method directly:
```
mxcube.set_aperture_diameter_microns(int(new_pos))
```
In practice `set_aperture_diameter_microns` could be a method of a super hwobj that has all hardware objects and the patching of actual implementation is done in a site specific way.

**Comment by bourenkov** [comment]
Hi Rasmus, 
What make this idea conceptually different from abstract HO (aside of Python3)?

**Comment by marcus-oscarsson** [comment]
Yes sorry Gleb I realize that I misunderstood your question. 

The contract Matias mentions is basically the definition of objects, methods signatures and data structures available available for each UI API, REST or other. My concern is also more about the
downstream part of the interface though.

What needs to be discussed more in detail is exactly what Ivars is mentioning, the design or composition of the core components that define the interface that we would like to share.

One could definitely imagine to access all methods directly on the mxcube object like Ivars suggests, or to have objects that group the methods in some way. Similar to what the diffractometer object does today. 

Many routines accesses several hardware objects so I can definitely see an advantage of having certain functions available directly on the mxcube or a beamline object. Like:

```
beamline.mount_sample_with_id(id)
beamline.quick_realign()
```

**Comment by bourenkov** [comment]
Hi Ivars,

Taking a point of view of someone who would be connecting the 
mxcube.set_aperture_diameter_microns(int(new_pos)) 
the real "beamline control" code, I would like to know:

- which aperture? I can have more then one at the beamline; even my diffractometer may have more then one.
- where should i move it to?
- in which context is it could be happening (e.g., aperture is bein set for data colection, or for beam position calibration, etc.)?
- should I synchronize the move?
- what the get_aperture should be doing before, after, during the move
+ many more 

there is a dozen on other considerations, of which effectively the configuration of the GUI/HOs, along with the HO code is currently taking care off right now. How would this happen with the new architechture?

**Comment by beteva** [comment]
Hi all, @IvarsKarpics is right, we should not assume if the device is a motor, actuator or a square circle. It should have some methods, common for any hardware implementation. And we should not be units dependant.
We also need to specify in the API which contract (in @mguijarr terms) it applies to, so there is no ambiguity which method to use.
In we take the aperture example, what I mean is: 
aperture = mxcube.diffractometer.getObjectByRole('aperture') this applies that the aperture belongs to the diffractometer contract
aperture.set_aperture(value)
aperture.insert() and aperture extract()
aperture.get_units()...
Last but not least, I would not bound the API to a Python version, as it might change.

**Comment by mguijarr** [comment]
There were 2 aspects in the proposal I made during our last meeting. One is the API to be defined, the other one is that we should simplify (or reduce?) what we consider MXCuBE is (let's call this 'MXCuBE core') and not to be too ambitious. This is why my talk was called 'Less is more'.

For example, we never managed to get good, clean abstract objects.

So, I would avoid objects as much as possible -- instead, I would define functions in the style of a REST API, with clear documentation : what is expected, what has to be returned (the contract).

Normally there should not be more than 120 functions ;)

The pragmatic approach I am advocating is to focus on interactions between User Interface and beamline, without thinking of making a full-featured beamline abstraction layer. Because at the end, MXCuBE is "just" an interface.  I admit this may sound controversial, please correct me if you think I am wrong.

If we manage to have the 2 UIs working with a functional, contract-based API, that we have tests and documentation -- then I would go one step further and try to have a real beamline abstraction layer. However, this implies dealing with the different control systems and I consider it more as a long term objective than something we should try to do again.

**Comment by rhfogh** [comment]
@beteva If you define the functions and parameters in one form (e.g. Python) it should be easy enough to translate it into another form - Python was just a nice place to start, since the code is in Python. I guess we could decide on a less powerful system, in order to support other languages, but I would rather not decide that e.g. all parameters must be defined only as strings (and passed accordingly). 

But what do you mean 'we should not be unit dependent'?  It is quite important to GPhL code  that you can make a function call that will query or set  e.g. the detector distance and that works at all sites. The simplest way is to decree that it must be set in mm, and let individual sites convert to their internal representation. If different sites use different units, how can I decide which value to send?

**Comment by marcus-oscarsson** [comment]
Each device that have an aperture should of course have the corresponding methods to control it, and one could imagine that one could access each of those through for instance (in the case of diffractometer):

'''
beamline.diffractometer.set_aperture_diameter(diameter, aperture=DEFAULT, usage=COLLECTION, wait=False)

args:
-----
diameter: float - the diameter in a suitable unit
aperture: enumerable - which aperture to set if there are several
usage: enumerable - defining the usage, data collection, callibration 
wait: boolean - wait for move to finish

emits:
-------
position_change - when the aperture position changes
state_change - when the state of the aperture changes, i.e. moving, ready

throws:
---------
The various exceptions thrown, one could for instance imagine
MoveFailed
'''

The method beamline.set_aperture_diameter can be seen as a convenience method that by default handle the most common case and once could take an extra arguments to handle each case that you would like to be available through this method.

For instance:
```
beamline.set_aperture_diameter(diameter, aperture=DEFAULT, usage=COLLECTION, device=DEFAULT, wait=False)
```

**Comment by rhfogh** [comment]
@bourenkov I think the interface and the abstract HO are very similar, conceptually - both specify a set of supported functions that you can code to. I guess the difference is that the HO we have now must support everything you might want the hardware to do. What we want to make now (however we implement it) we want to have only those functions that are needed to access from outside the 'component', or from the UI.

**Comment by rhfogh** [comment]
@bourenkov, @marcus-oscarsson 
I am not sure you want this level of detail in the interface. You need to identify the right aperture, obviously, and you need to pass the right value. But the usage context, whether you should wait, whether you should synchronise, why does the UI need to keep track of that? Could you not say that if you are changing the current value it changes. Now. Alternatively you are passing the value to a queue_model_object, and when the queue is executed it (on the beamline side, not the UI side) it will know what the context is, and whether to wait, synchronise etc.

**Comment by marcus-oscarsson** [comment]
@rhfogh 

Well we don't want it that level of detail between the UI API's and COMMON UI API but we would eventually need it between the COMMON UI API and the CORE COMPONENTS / BEAMLINE CONTROL. So I can understand @bourenkov concern and the discussion is interesting, although I think that we should focus on the definition of the COMMON UI API to start with.

**Comment by rhfogh** [comment]
@marcus-oscarsson I am a little confused by your terms. How do you define the UI APIs and the COMMON UI API, and how do they differ?

**Comment by marcus-oscarsson** [comment]
Well wee need a way for each UI to adapt to the COMMON UI API if they cant use the same technology, The Qt application need an alternative to the REST services, or at least that's what I assume for the time being. If its not the case, well that just makes tings much simpler.

The COMMON UI API would basically just be the set of functions and signals that each UI specific API need to call. Similar to what we are doing in MXCuBE3 today.

**Comment by rhfogh** [comment]
@marcus-oscarsson OK, the words makes sense. So we have the two UIs, each on top of a UI-specific API. Those, again, are on top of a COMMON API, which is on top of the components/beamline layer. Right? 
![image](https://user-images.githubusercontent.com/9820176/37158234-cd91b0b0-22e2-11e8-9ca7-e63536219bac.png)
But why would we need those details in the COMMON API layer, if they are not in the UI API layers? Is this not the kind of thing you would want to encapsulate? The detailed control is certainly needed within the components, possibly between the components, but in the UI API layer?

**Comment by marcus-oscarsson** [comment]
Well I tired to explain it in my initial post where I also included a figure similar to the one you just made.
What I meant to say was that the detailed level of control is needed between the COMMON UI API and what you call Beamline/Component layer in your figure above. Perhaps more in the Beamline/Component layer though, that remains to be seen.

**Comment by bourenkov** [comment]
@rhfogh 
If we agree on  Mattias' proposal - functions vs objects - the discussion on abstract classes vs abstract HOs becomes obsolete. For completeness - as far as I can see existing abstract (and generic and mockup) HOs do exactly nothing; but they were simply not used.

@rhfogh @marcus-oscarsson 
If we agree that API is a documented definitions of a set of functions, then the level of details should be sufficient to implement the downstream layer (without recurring to experimental programming). I.e., the part of the contract should be specified as well, something like (out of blue sky):

beamline.diffractometer.set_aperture_diameter 

usage=COLLECTION: setting the aperture is commanded by the queue. Unless "wait=true",  the caller assumes that the beamline control will take care about starting the next collection with the right aperture in place. Exception will interrupt the collection preparation sequence.

usage=WIDGET : user commands aperture via the pop-up menu. All GUI triggers requiring diffractometer (ref. to the list of those) will be blocked before sending the command and released when "state_ready" is emitted or exception is thrown. If exception is thrown but state_ready is not emitted, only the aperture widget and "start collection" buttons will stay disabled.

@all
Can we write up one such example - lets take this Aperture - complete and in a shape which will suit both GUIs?

**Comment by marcus-oscarsson** [comment]
@bourenkov  @ALL

I've tried to come up with an example based on our discussion around the aperture. We are currently don't have a feature that handles several devices with apertures, like a complex beam shape definer, that you are referring to earlier. So my example is limited to the traditional diffractometer aperture that we have today.

The example is based on what we are doing today in MXCuBE3 but adapted to the structure that we have been discussing here. We are never passing the wait argument from the UI but its defined in the beamline control layer, in the case of the aperture we are passing wait=True. But keep in mind that the client is completely asynchronous and keeps on doing other things until the call(s) have finished. We are relying on the status code often set through exceptions to handle any errors. 

The usage parameter will as far as I understand always be WIDGET/UI within the UI LAYERS so I have excluded that as well. So for MXCuBE 3 concerning the aperture we can say that wait=True and usage=UI all the time. You seem to have more requirements regarding apertures so feel free to complete my example with your needs:

```
# Beamline control layer
# Needs to define an object, likely a singleton, that provides access to the 
# different core components, one of them being the beamline object
# which in the example code below is assumed to be a available globally.

# The COMMON UI API will define expected signatures and to some extent behavior
# of the functions in this layer,  for the set_aperture method on the aperture object or similair
# that could be something like:

def set_aperture(self, diameter):
"""
ARGS:
diameter: float - the diameter (in microns)

EMITS:
position_change - when the aperture position changes
state_change - when the state of the aperture changes, i.e. moving, ready

THROWS:
The various exceptions thrown, one could for instance imagine
MoveFailed
"""

# REST UI API LAYER (MXCUBE3 Specific)
@mxcube.route("/mxcube/api/v0.1/diffractometer/aperture", methods=['PUT'])
def _set_aperture():
    diameter = request.get_json().get("diameter", "")

    # Errors setting value should be handled in the try except
    # Sanity checks of the values to be done within beamline control layer
    # and propagated upwards as an exceptions so that the caller can handle
    # the problem.
    try:
        set_aperture(diameter)
    except ApertureRelatedErrors, OtherErrors:
        return Response(status=409)
    else:
        return Response(status=200)

@mxcube.route("/mxcube/api/v0.1/diffractometer/aperture", methods=['GET'])
def _get_aperture():
    try:
        resp = jsonify({"aperture": get_aperture()})
        resp.status_code = 200
    except ApertureRelatedErrors, OtherErrors:
        resp = Response(status=409)
    
    return resp

@mxcube.route("/mxcube/api/v0.1/diffractometer/available_aperture_list", methods=['GET'])
def _get_aperture_list():
    try:
        resp = jsonify({"aperture": available_aperture_list()})
        resp.status_code = 200
    except ApertureRelatedErrors, OtherErrors:
        resp = Response(status=409)
    
    return resp

# COMMON UI API
def available_aperture_list():
    """
    Returns a list of available apertures (microns)
    :rvalue: List of float values (diameter of apertures)
    """
    return beamline.diffractometer.available_aperature_list()

def set_aperture(diameter):
    """
    Set the diffractometer aperture to <diameter> microns
    :param float diameter: diameter in microns

    Expected to throw:
    ApertureError - 
    """
    beamline.diffractomter.set_aperture(diameter)

def get_aperture():
    """
    Returns the current diffractometer aperture
    :rvalue: float (microns)
    """
    return beamline.diffractomter.get_aperture()

def aperture_position_change_cb(diameter):
    """
    Callback to be called when the aperture position changes
    :param float diameter: the new diameter in microns
    """

    # dispatcher have to be defined within the UI specific API
    dispatcher.emit("aperture_diameter_change", {"diameter": diameter})

def aperture_state_change_cb(state, diameter):
    """
    Callback to be called when the aperture state changes
    :param float diameter: the new diameter in microns
    :param str state: One of the predfined states ["READY", "MOVING", "ERROR"]
    """
    # dispatcher have to be defined within the UI specific API
    dispatcher.emit("aperture_state_change", {"diameter": diameter,
                                                 "state": state})

def aperture_async_error_cb(error, state, diameter):
    """
    Callback to be called when an error occurs and the action was asynchronous 
    :param float diameter: the new diameter in microns
    :param str state: One of the predfined states ["READY", "MOVING", "ERROR"]
    :param str error: str representation of error state or exception
    """
    # dispatcher have to be defined within the UI specific API
    dispatcher.emit("aperture_async_error", { "error": error,
                                              "diameter": diameter,
                                              "state": state})
```

**Comment by bourenkov** [comment]
@marcus-oscarsson 

It would help me a lot if there would be a brief but complete description of how MxCuBE3 handles the apertures. Apparently I do not understand that. E.g.:

- Is one of the "diameters" from that list sits on the beam at _all_ times, and the _only_ handle that user has is to replace it with another one from the list?  
- What are the other things which client (the GUI?) lets user do while the aperture is moving? Will it also send other commands to the diffractometer?
- What happens when callbacks are emitting - each of the three?
- When and why the "_get_aperture" would be called? 

It seems like we indeed have more requirements on the aperture. Your may that in https://github.com/mxcube/HardwareRepository/blob/master/HardwareObjects/EMBL/EMBLAperture.py. In fact I can not remember all details of how Qt4 MxCuBE handles apertures, I need to get back to it before I can start extending the example.

**Comment by marcus-oscarsson** [comment]
@bourenkov, @ALL

So the example is an adaption of what we have to the current suggestion, so its deviating a little bit from how its done today.

The aperture in MXCuBE3 works very similar to MXCuBE2 Qt3. There is a dropdown list with available apertures for the user to choose between. The values currently corresponds to the available diameters, one could of course imagine that this list simply gets longer if you have a more complex setup. It would then perhaps be better if the COMMON UI layer just takes an aperture identifier like "Circle 30", instead of micron values, and the control layer takes care of the rest.


It would help me a lot if there would be a brief but complete description of how MxCuBE3 handles the apertures. Apparently I do not understand that. E.g.:

- _Is one of the "diameters" from that list sits on the beam at all times, and the only handle that user has is to replace it with another one from the list?_

- Yes the user chooses one of these apertures from the dropdown list, actually what is sent to the hardware control layer is the position that corresponds to what the user have selected. But the user only sees the corresponding micron values.

- _What are the other things which client (the GUI?) lets user do while the aperture is moving? Will it also send other commands to the diffractometer_?

- The user could theoretically send, as far as I remember, any action to the diffractometer while changing the aperture. Although all user actions on the hardware are disabled while collecting. There is a signal that blocks user actions, this can be generalized to not only include include collect.

- _What happens when callbacks are emitting - each of the three_?
- We are not using async_error_cb that was only an example to have a more complete example on how we could handle async errros. The other two are used when the aperture is changed from outside of MXCuBE.

- _When and why the "_get_aperture" would be called?_
  
- The get_aperture is called when the client connects or reconnects (page refresh) to get the current aperture

**Comment by rhfogh** [comment]
@marcus-oscarsson @bourenkov @ALL
I have a couple of questions for the discussion on Monday:

- usage:WIDGET v.usage:COLLECTION:
  If I have it right, this is the difference between setting the current value of something, and setting a value in the queue_model_object for later use. In the latter case, is it always clear which collection(s) you are talking about? if there is more than one collection on the queue, which one(s) does it apply to - and do we not need something more explicit to keep track of that? Would we always want the user to be able to change something on 'the next collection', possibly in the middle of a series? GPhL workflow sets up several consecutive collection events in one go, all on the same sample, but with e.g. different wavelengths. 

- Multiple apertures / motors:
  It looks like different beamlines will have different combinations of apertures, and other motors etc. might vary as well. How will that translate into a generic interface for a generic UI? Should the interface have explicit slots for all the apertures that could arise? Should it simply allow for n apertures (or n motors) with some kind of addressing mechanism to decide which one? How, and how site-specific, should the UI be to accommodate the different set-ups? And (asked in ignorance) might it be possible to set a parameter like 'beam-size' (much as you scan et 'resolution' rather than 'detector_distance') and leave it to hardware-side code to translate that to actual apertures?

**Comment by bourenkov** [comment]
@rhfogh @ALL

Summarising discussions, here and in-person with Marcus and Daniele (as I happen to visit ESRF earlier this week), here are the conclusions:

a) We are lucking a very basic knowledge of how various core components (devices, procedures and workflows, - in particular the apertures) are implemented and being handled in different setups. 

b) The first, necessary step towards developing a unified APIs should be to write up exact and detailed specifications for those core components. This specifications must cover the variations across different sites.

c) The set of the core components to be addressed, in order of priority, could be:
I.
a) diffractometer (including all its sub-devices like an aperture device)
b) sample changer
c) data collection
d) basic meta-devices : detector distance, energy, transmission
e) queue
II. 
e) ISPYB interface
f) XRF and energy scans
g) External exp. control
...
III. 
... 

Concerning the details of Aperture example:

- In MxCuBE3, there is always one (let's call it "active") aperture sitting on the beam in front of the video microscope objective. There is only one action on aperture possible, via a widget  :  start setting another "active" aperture, immediately, asynchronously.

- In Qt4 MxCuBE (at EMBL-HH at least), during the "Sample Centring" phase the apertures are physically kept at a so-called "Off" position. This is essential in order prevent degradation of the sample image in the video microscope. Thereby, the "active" aperture value is defined at all times. In the "Data Collection" phase, which is set before any data collection, the current "active" aperture will be set into the beam. In all phases, the value of the "active" aperture size in combination with other beam defining elements -  mirrors, CRLs and slits at P14 (or none at P13), is used to determine the beam size and shape to as video overlay, for dose calculations and to record beam parameters in ISPYB. User can choose the "active" aperture and drive it on "Off/On" position via a widget.

- at the moment neither Qt4 MxCuBE2 nor MxCuBE3has a capability of queuing collections with varying apertures. The last "active" aperture chosen before the beginning of queue execution will be applied to all queue entries. During the queue execution the aperture widget is blocked.

**Comment by mguijarr** [comment]
From the description of the aperture example above, here is my understanding of the support needed
in MXCuBE "core" to implement this feature:

* communication from the back-end (or "common API layer") to inform UI about active aperture state
* communication from back-end to UI to inform about beam size and shape updates
* communication from UI to back-end to tell which aperture is the active one
* communication from UI to back-end to set aperture on or off

(maybe the last 2 can be combined)

So it is only 2 signals and maximum 2 API calls to be defined -- it would make both MXCuBE 3 and
MXCuBE Qt4 user interfaces happy.

I would consider:

* moving aperture to 'Off' position when centring starts
* setting active aperture when data collection starts
* specific determination of beam shape and size depending on aperture and other elements

to be left as particular implementations of the back-end logic, out of the scope of "MXCuBE core" (if we re-center the collaboration around something easier to maintain and focused to the User Interface as I proposed).

An extra "Aperture" data collection parameter can be added, to be able to queue collections with varying apertures (new feature).

**Comment by bourenkov** [comment]
@mguijarr 

I perfectly agree with all that. 
Perhaps, the fifth communication of available_aperture_list() should not be forgotten. 

But, I would like to stress once again that such a support in the mxcube core will only be useful if we provide it along with specifications of how these communications are used in the context of existing UIs. These specifications must be sufficient for an abstract back-end developer to understand what the meaning of "active" and "off/on" is and what do with those in his particular setup.

**Comment by marcus-oscarsson** [comment]
I originally posted this on the MXCuBE3 repository but I realized that maybe not everybody is subscribed to changes made there, so I'm also positing it here.

This is a very preliminary design document to be used as background for the ongoing discussion. I hope to be able to complete it with more information until our meeting the 12th of April.

I've decided to distribute this as PDF and I will create a new entry for every update I make.
[MXCuBE3 - Design (1).pdf](https://github.com/mxcube/HardwareRepository/files/1897547/MXCuBE3.-.Design.1.pdf)
. Its for the moment the easiest way that I found to be able to reuse the content in a convenient way later.

Please let me know if there is anything in particular you are missing or that you would like to know more about and I will try to focus on that.

**Comment by IvarsKarpics** [comment]
Hi all,

Some time ago I started to define abstract classes:
https://docs.google.com/document/d/16VY5xqzuMr3Ic7_Ty5Zz11EaR4uPMTcl2hdEOzMS25E/edit
This could be a proposal how to define a common API to hardware objects.

Ivars

**Comment by jordiandreu** [comment]
Hi everyone,

Until last comment from @IvarsKarpics, the vast majority of the entries in this issue were related to the API between the core components and the UI. However, as it was mentioned as the first aim of this refactoring issue and also in the document attached by @IvarsKarpics , also the API between core components (or HwObjs) is responsible of the complexity in the application structure.

Focusing only in the UI API maybe is not sufficient to reduce the ecosystem of specific HwObjs. 
Having many specific basic component could not be a big deal, but define the complete API that each core component (or HwObj) should expose not only to the UI, but also to the other components, would be of interest for current and future developers.

Jordi

**Comment by marcus-oscarsson** [comment]
Dear Jordi, All,

Yes you are right in that the task also was to refine the design of the core components, but it was at the same time decided at one of our first meetings, if not the first, that the first thing we would do was to focus on the UI API LAYER. Then continue with the core component refactoring/redesign when the first task was done.

I tried to outline in my background that we probably need a new design that replaces or updates the HardwareRespoitry and HardwareObjects which is more in line with how people do instrument control today. With lack for a better word we have referred to this as CORE COMPONENTS. 

I would be very happy to continue the discussions around this new design of the core components, I have some ideas in store for this since some time already. But I think that we need to focus the task that we already started and then tackle the core components.

Cheers,
Marcus

**Comment by rhfogh** [comment]
Dear All,

We did agree to start to start with the interface to the UI - not just because you have to start somewhere, but to keep the task small enough to ensure that it actually got done. And I agree that we should avoid confusing or complicating the task in hand. For now, the UI interface is the only point that the developers' group is officially engaged with, and we need to get that done fairly urgently.

On the other hand, rationalising the hardware level would be a great advantage and is arguably something that needs doing for the long term future of the project. It is surely not something we should discourage people from working on, as long as they can find the additional time. And it seems to me that any sensible introduction of abstract objects is bound to be an asset later, no matter what overall structure we might eventually go for. 

I would propose making a separate github issue for hardware level refactoring, where those who are interested can  discuss the matter. We can then leave the hardware level to one side until such a time as the full developers' group wants to take it up. Obviously whatever might be agreed in the hardware object discussion will not be binding on those who do not chose to participate!

Incidentally, I think it would be useful to see the UI interface we are now working on as being determined by the UI side only - which information to show, which values to set, which commands to send, ... If it is not in the actual UI, it does not belong. That gives a simple test for what should be done where.

**Comment by jordiandreu** [comment]
Dear All,

I apologize, I was not in the last meeting at Diamond and I had not the minutes in mind. Certainly, the developers' agreement was to start with the interface to the UI.
Sorry for messing the conversation a bit and lets discuss about the HwObj/CoreComponents in a different issue (or even in future meetings).

Cheers,
Jordi

**Comment by IvarsKarpics** [comment]
Superseded
