### ISSUE TITLE
Centring when mounting sample not working

### ISSUE THREAD

**Issue by rhfogh** [mxcube/HardwareRepository#153]
In my hands, in mock mode, the queue_entry.manual_centring function does not work, after my recent PR at least.
The call        dm.start_centring_method(dm.MANUAL3CLICK_MODE)
puts the program in a state where it is not responsive to mouse clicks, and no centring happens.
In the end I have to stop the centring, click Save, and then do centring later.
Not sure how to fix that, since calling Qt4_GraphicsManager from queue_entry does not seem acceptable.

**Comment by IvarsKarpics** [comment]
Hi @rhfogh ,

I will have a look at this issue.

**Comment by rhfogh** [comment]
Thanks for the fix, Ivars.
