### ISSUE TITLE
Need write access for rhfogh

### ISSUE THREAD

**Issue by rhfogh** [mxcube/HardwareRepository#159]
I should accept PRs #157 and #158 - I have done the testing and no one else has looked at it for a while. But I do not have write permission for this repository after all. Could someone give me the permission?

**Comment by IvarsKarpics** [comment]
Hi,

I added you as a collaborator. You should be able to accept PRs.

**Comment by IvarsKarpics** [comment]
I guess you have to accept the invitation. see: https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/
