### ISSUE TITLE
Video height and width handled inconsistently

### ISSUE THREAD

**Issue by rhfogh** [mxcube/HardwareRepository#250]
Width and height of video is handled sin some places through the image_dimensions attribute, in some places via a call to get_eraw_image_size() (via the get_image_dimensions() function). The attribute GenericVideoDevice.raw_image_dimensions seems not to be used.

This clearly will likely lead to mistakes down the line, and needs looking at by someone who understands that part of the code.

**Comment by IvarsKarpics** [comment]
@rhfogh  is this still an issue?
