### ISSUE TITLE
from x import *

### ISSUE THREAD

**Issue by rhfogh** [mxcube/HardwareRepository#288]
'from x import *' is bad style, and leads to confusion as to what is imported where. 

Most cases are too idiosyncratic for strangers to meddle with, but I would volunteer to clean up for 
'from TaskUtils import *' (present all over the place in various people's code),
and 'from queue_model_enumerables_v1 import *' (present in queue_entry only). 

Does anybody want me to do it, or should I just leave things as they are?

**Comment by IvarsKarpics** [comment]
Hi @rhfogh ,

I fully support not using * import and added label 3.0.0 to the issue. Please go ahead an prepare a PR to fix the TaskUtil, the queue_model* can be fixed within issue #274

**Comment by IvarsKarpics** [comment]
Solved via #287
