### ISSUE TITLE
Adding __category__ label

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/HardwareRepository#298]
What about adding a `__category__ `label to the hardware objects? In the qt bricks __category__ is used to sort all bricks in the available bricks tree. In this case it would be useful to see it in the summary log:
```
+ ============================================================================== +
| Xml                      | Class                      | Category |Load time | Comment|
+ ============================================================================== +
| /Qt4_graphics-manager    | Qt4_GraphicsManager        | Graphics | 7 ms    |    |
| /Qt4_video-mockup        | Qt4_VideoMockup            | Graphics |104 ms   |    |
| /attenuators             | Attenuators                |  Beam    |23 ms    |    |
```
And maybe in the future it could be possible to do some clever imports like

`from motors import TangoMotor`

**Comment by beteva** [comment]
This is a good idea. There used to be something like that fro the Bricks. We should not abuse, though, with the number of categories we create. It is also essential to agree on the category names before applying the rule.
This is my proposal for the list of categories: positioning (all motors, piezos, encoders), detectors (pixel, MCA, cameras), io (input/output - actuators), instrumentation (diffractometer, beamstop, ...)  and sequence (collection, XRF, energy scan, workflows, ...). Did I forget anything?

**Comment by marcus-oscarsson** [comment]
I think I would prefer to derive that kind of information from its abstract base class

**Comment by IvarsKarpics** [comment]
Use abstract classes to deriver new classes. api/beamline object to be initialized via config file and not categories
