### ISSUE TITLE
What happend to mock configuration xml's?

### ISSUE THREAD

**Issue by rhfogh** [mxcube/HardwareRepository#305]
Maybe I am stupid, but the configs for the mock objects used to live in the top directory ExampleFiles/HardwareObjects.xml/. Now after accepting the PR that moved the site-specific configs I cannot find the mock ones. Where should they be?

Yes, I know I was the one who merged that pull request, but you  can hardly review 800+ files that move, can you?

**Comment by IvarsKarpics** [comment]
Hi @rhfogh 

Sorry for not adding description to the related PR. Example config for qt version you can find in https://github.com/mxcube/HardwareRepository/tree/master/test/xml-qt

**Comment by rhfogh** [comment]
As expected, there was a simple answer.Good. Thanks.
