### ISSUE TITLE
What does HardwareRepository/test/xml do?

### ISSUE THREAD

**Issue by rhfogh** [mxcube/HardwareRepository#319]
Just a question: 

in HardwareRepository/test we have xml-qt/ (OK) and xml-web/ (OK), and plain xml/. What does the last one do - the contents overlap with xml-qt? Is it for UI-independent configuration? Is it obsolete? Should I rely on it or ignore it?

**Comment by IvarsKarpics** [comment]
Hi @rhfogh ,

I had the same question :) I guess it is a leftover?

**Comment by marcus-oscarsson** [comment]
Hi,

Yes its a left over, it can be removed as long as whats in configuration is up to date, I noticed that there are for instance no configuration for mockups, qt or web, in the configuration folder. 

Marcus

**Comment by rhfogh** [comment]
Actually, I thought it might be a good idea to have a single location for mockups that do not depend on the choice of UI. Why do we need two different mock=ups for mxcollect, for instance, or for the motor objects? But other people might have a counterargument.

Another question is whether this shared mockup directory belongs in configuration or in HardwareRepository/test. What do people think?

**Comment by IvarsKarpics** [comment]
Hi @rhfogh ,

I agree that a single config directory for both ui is a good solution. Then we will avoid confusion and the maintenance is easier. I have a running mockup version of qt and web and can sort out this.

**Comment by rhfogh** [comment]
That would be great.
