### ISSUE TITLE
configuration XML files (configuration and test/xml*)

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/HardwareRepository#321]
Hi,

There are still some configuration XML files in /test/xml*, that should be moved to the new configuration folder.

**Move relevant xml files from /test/xml\* to /configuration**

Marcus

**Comment by rhfogh** [comment]
Should there be a single top=level set of UI-independent mock configs? And if so where?

**Comment by IvarsKarpics** [comment]
Hmm, I thought we agreed on two directories: configuration (site specific config) and tests/xml*, or it should be a single directory?

**Comment by rhfogh** [comment]
That sounds logical. I guess that means we should put the UI-independent mock configs in test/xml/ ?

**Comment by marcus-oscarsson** [comment]
Not so sure about that, I think that the mockup xml files should be in configuration as well. It's the configuration files for the mockups right ?. Seems unnecessary to me to have these in two different places.

@rhfogh Not sure what you mean by UI-independent, the xml files configure hardware objects and should all be UI-independent. Thy application (UI) using the hardware objects might rely on that a certain configuration exist.

It would be good as you noted in the PR if the qt and web mockup xml files are the same, we have to see if the defaults used are the same before though.

**Comment by IvarsKarpics** [comment]
I started by removing the not used xmls in test/xml: see PR #323

**Comment by IvarsKarpics** [comment]
I somehow agree on moving test xmls to configuration, but directory test should stay because it contains pytest for travis
