### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/HardwareRepository#330]
Should we have a file called RELEASE_NOTES to keep a track on changes and have some information when we make a release? It could be an edited file where we add all changes that will be available in the release. Something like:

11.03.2018 - v3.0.0.

* Configuration xmls moved to configuration directory.
* Added travis CI
* ...

Then when we make a release we just copy the information from the RELEASE_NOTES

**Comment by marcus-oscarsson** [comment]
Its true that its somehow handy, the only small drawback I see with it that its kind of a duplication of whats in Git already. I usually scan Git log and add the essential information when I tag. Another way would be to extract all the finished/done issues/tasks.

However it is a bit tedious to do this, especially when we are several people developing with no clear commit message style :). So why not, but then we also need to keep this file up to date.

I would be more in favor of either extracting it from the Git log or from the issues, as long as we can agree on how to work either or both :)

**Comment by jordiandreu** [comment]
We can get inspired by:

https://keepachangelog.com/en/1.0.0/

For instance, ALBA is applying this to Sardana project (see https://github.com/sardana-org/sardana/blob/develop/CHANGELOG.md)

I  my opinion, the changelog should contain information useful also for the final user or who reports an issue and be maybe less technical or with less detail that the git commit message.

Clearly, an automation of the changelog update would be appreciated.

**Comment by jordiandreu** [comment]
In Sardana, the changelog is edited by hand just following the information described in the issues i.e there is no automation from git messages (FYI, they work in a 6-months Release scheme). 

I general, a single entry in the changelog (for instance, a bug fix) could correspond to several git commits. In this sense, I think there is not straight forward the correspondence between git commits and changelog entries. I would be more in favor to link the changelog entries to issues (even there is not a one-to-one correspondence either!).

In the other hand, I heard opinions about how to format git commit messages ans style rules:

https://chris.beams.io/posts/git-commit/

I think interesting to include some advice/rules/policies in the developers guide about the commit messages following these ideas.

**Comment by marcus-oscarsson** [comment]
I see, yes well there will as you say unlikely be a one to one correspondence between git log or issues to an entry in the changelog. There is however plenty of information in both those places that could be extracted for a draft version of a change log, that could be later edited/reviewed by hand before a release is done.

The general outline of whats proposed on keepachangelog.org looks good to me. I also think it would be great if we could agree on someway to format the commit messages. The important thing for us developers is of course that this is all in the end convenient to use, the more convenient the more likely it is that its going to be used. Convenient both to add the information and to use it of course.

The problem with a completely manual changelog in a "distributed" project like this is that each developer needs to continuously keep the changelog up to date, something that is prone to be forgotten or done sporadically and things are easily missed as a consequence. I would personally not like to, if it can be avoided, write a commit message (and sometimes open and close an issue) and then add an entry in a changelog as an additional step.

One might imagine that one tags the commit messages with for in stance #CH:ADDED#, #CH:FIXED# and so on if the commit message contains information one would like to add in a change log.

The additional advantage with this is that one gets the dates, author and possible also which issues it solves (if one uses for instance fixes: #NNN). This could be used to create a draft changelog from the commit log that can be easily edited by hand and reduces the risk that things are forgotten.

Then again I think its better having a changelog than not having any so if everybody else thinks keeping a manual changelog is the only solution I'll be happy to contribute to it.

**Comment by IvarsKarpics** [comment]
- Each release should contain release notes.
- Webpage should contain link to the latest release of mxcube2, web and hwr.
- Add more info to the webpage about mxcube
