### ISSUE TITLE
Sphinx doc string style

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/HardwareRepository#337]
Agree on sphinx doc string style,

Original: https://www.sphinx-doc.org/en/1.5/domains.html?highlight=param
Google: http://www.sphinx-doc.org/en/1.5/ext/example_google.html
NumPy: http://www.sphinx-doc.org/en/1.5/ext/example_numpy.html#example-numpy
Other: ?

**Comment by rhfogh** [comment]
In a former job I had a set-up where a minor plug-in to sphinx took the PEP 484 annotations (':int' etc.) and put those in the doc string for the documentation. Together with good parameter names that actually gives decent documentation for very little effort. Of course you still need explicit doc strings for some funstions and parameters. And, of course, it requires Python 3. When can we get that?

**Comment by marcus-oscarsson** [comment]
@rhfogh: I don't know when we will have Python 3 support yet we should perhaps discuss a more exact date for it. We also need to consider if we want to be Python 2.7 compatible since these type annotations are not. 

There might still be sites that are not ready to jump to Python 3 just like that. That does not however prevent us from using Python 3 we just have to make sure not to use certain features right away.

Sphinx already supports type documentation so we should still add that regardless of python version :)

**Comment by IvarsKarpics** [comment]
I would vote for the google style.

**Comment by beteva** [comment]
I also vote for the google style. There is a nice tool to be used as well:
https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html

**Comment by rhfogh** [comment]
Indeed. Looks good.
