### ISSUE TITLE
Refactoring and Yaml-configuration for HardwareObjects

### ISSUE THREAD

**Issue by rhfogh** [mxcube/HardwareRepository#404]
Once the BeamlineObject (#402) is in and we start refactoring HardwareObjects, we might consider whetehr we should simplfy the current set-up and use the Yaml configuration also for HardwareObjects. WIth some limited refactoring up front (see #403), I see two questions:

- Can we get rid of HardwareObjectNode and replace it with ConfiguredObject? The biggest question is whether all the functions to deal with XML configuration, objetcs, references, properties, names, paths, and roles can be replaced with the much simpler set-up in ConfiguredObject, or if (how much?) we need the relevant functionality, and for what. Also, do we need the funtionality to treat a HardwareObjectNode as a map and a collection (__getitem__, __iter__, __len__, ...) or would it not be simpler to get rid of it?

- Are there functions in HardwareObject we could get rid of: xml source getting and rewriting?__bool__,  __nonzero__,  __getstate__? __getattr__ resricting attribute acess? Or what is the functionality we need to have (and where is it documented)?

**Comment by marcus-oscarsson** [comment]
It was decided to keep the possibility to use xml files to facilitate the migration to new version of HardwareRepository.
