### ISSUE TITLE
Move undulators from HWR.beamline to HWR.beamline.energy

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/HardwareRepository#429]

**Comment by beteva** [comment]
Could you, please, explain why. Normally undulators do not depend on the energy.

**Comment by IvarsKarpics** [comment]
Yes, but energy depends on the undulator gap. The only place that needs the gap(s) is the lims hwobj and I am in favor not to put everything on the beamline level. Although I am open for a discussion.

**Comment by rhfogh** [comment]
I would vote for putting it in Energy as well, on general principles (though without having thought deeply about this particular case).

**Comment by marcus-oscarsson** [comment]
Decided on developers code camp, will be added to Beam Object inheriting AbstractBeam
