### ISSUE TITLE
Implementation of Data Objects

### ISSUE THREAD

**Issue by rhfogh** [mxcube/HardwareRepository#433]
@marcus-oscarsson proposes a DataObject that is essentially a frozen, nested diftionary with an associated JSON schema for specification and validation. If you are thinking in terms of sending data  objects over a network this is clearly very suitable - seeing as you need to make the JSON anyway. And this is clearly a very important use case, particularly for procedures. 

If you think in terms of specifying the Python functions that execute operations, like Collection, I have some problems with it. Here more standard Python solutions, like the DataObject class (3.7 adn above) or .attrs module (2.7 and up) have some advantages. I think we should discuss which solutions we could use for which use cases.

Concerns with the JSON schema approach:

- The specification is outside the body of code, in a verbose form that is less readable than the Python modules. That coudl get tricky for sdubtle points: Are collection parameters a single dict, or a list of dicts (multi-wedge)? How is interleaving handled? How does it change between beamlines? A JSON schema (do they allwo comments?) may nto be the best place to keep track. 
- The specification is not accessible to linters (like Codacy) or Pycharms pylint.
- There is no mechanism for subclassing, or for ensuring that the data passed to the generic version (in the Abstrract class) are supported by, or compatible with, the version specified in a beamline-specific version. With a DataObject you can add additional parameters (with defaults) in a subclass; with JSON schema every schema is separate, also from the ones used in the subclass. 

The use in AbstractCollect is a good example: All data transfer is inside a single class. In order to see what attributes are available I need to go to the JSON schema. And if people use a different JSON schema in a Beamline-specific subclass, there is no way to see or check whether the top level code matches the beamline-sopecific code. By careful coding we can of course makes sure that functions that might need to be called from Python code have compatible signatures on different beamlines, but it would be easier if the coding approach supported it.  

Can anybody see a way to do something about these concerns, at least for cases where we are interested in calls between objects in the hardware and queue layer? Or should we notionally convert our data to JSON (wuith schema) even in those cases?

**Comment by marcus-oscarsson** [comment]
As I mentioned before I would really prefer that we keep closely related topics in the same place. I've already done a few comments on this on #426. 

> @marcus-oscarsson proposes a DataObject that is essentially a frozen, nested diftionary with an associated JSON schema for specification and validation. If you are thinking in terms of sending data objects over a network this is clearly very suitable - seeing as you need to make the JSON anyway. And this is clearly a very important use case, particularly for procedures.
> 
> If you think in terms of specifying the Python functions that execute operations, like Collection, I have some problems with it. Here more standard Python solutions, like the DataObject class (3.7 adn above) or .attrs module (2.7 and up) have some advantages. I think we should discuss which solutions we could use for which use cases.

I agree that Data Classes would be an ideal solution but we can use them yet as we have said that we want to be Python 2.7 compatible. I think its important that we are able to use the same Data Object in both Python 2.7 and 3. I've not used the .attrs module, the syntax looks slightly odd at a first glans but that's maybe just me ? It would be quite important, almost a requirement, for us to get a JSON Schema out of it could .attrs do that ?

> 
> Concerns with the JSON schema approach:
> 
> * The specification is outside the body of code, in a verbose form that is less readable than the Python modules. That coudl get tricky for sdubtle points: Are collection parameters a single dict, or a list of dicts (multi-wedge)? How is interleaving handled? How does it change between beamlines? A JSON schema (do they allwo comments?) may nto be the best place to keep track.

The specification would be in your class definition and there is support for nested sachems:
    https://json-schema.org/understanding-json-schema/structuring.html
And you can normally comment with //

> * The specification is not accessible to linters (like Codacy) or Pycharms pylint.
It would perhaps be available if you install a json-schema extension to your editor ?
There is for instance one VSCode which I use but I don't know if it does exactly what you like ...

> * There is no mechanism for subclassing, or for ensuring that the data passed to the generic version (in the Abstrract class) are supported by, or compatible with, the version specified in a beamline-specific version. With a DataObject you can add additional parameters (with defaults) in a subclass; with JSON schema every schema is separate, also from the ones used in the subclass.

You are right It would be complicated to provide a mechanism for inheritance. Again we can't use Data Classes with our current commitment.

> 
> The use in AbstractCollect is a good example: All data transfer is inside a single class. In order to see what attributes are available I need to go to the JSON schema. And if people use a different JSON schema in a Beamline-specific subclass, there is no way to see or check whether the top level code matches the beamline-sopecific code. By careful coding we can of course makes sure that functions that might need to be called from Python code have compatible signatures on different beamlines, but it would be easier if the coding approach supported it.

I'm not sure there would be much of a difference, I guess you mean that this would be made easier if we could inherit some base set of parameters ?. Would it be strictly necessary or even a good idea to pass those as the same object ?

> 
> Can anybody see a way to do something about these concerns, at least for cases where we are interested in calls between objects in the hardware and queue layer? Or should we notionally convert our data to JSON (wuith schema) even in those cases?

I think it would be great if we could use the same DataObject everywhere not only for collect related routines. Data Classes would solve that problem and would perhaps not be a problem depending on how we tackle the Python 3 and Python 2.7 compatibility issue ?

**Comment by marcus-oscarsson** [comment]
I'm away tomorrow and Monday is public holiday here in France so I have not lost interest if I'm not answering ... I'm just away for a few days ... This is maybe a topic to keep for the developers face to face meeting as I imagine that its something that is fairly easy to settle face to face and a bit more complicated like this ?
