### ISSUE TITLE
Rename AbstractMicroscope to AbstractSampleView

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/HardwareRepository#449]
Rename AbstractMicroscope to AbstractSampleView and Microscope to SampleView

AbstractSampleView derive from HardwareObject (As all Abstract objects)
Add the attributes:
- graphics
- shapes
- zoom
- front_light
- back_light 
- camera
- get_snapshot(overlays=boolean)
- ...

**Comment by IvarsKarpics** [comment]
see PR #470

**Comment by marcus-oscarsson** [comment]
Done
