### ISSUE TITLE
Filling RobotAction table for robot load times

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/HardwareRepository#467]
Orignal issue from Stuart Fisher:

> Could mxcube please populate RobotAction when a sample is mounted. There is already a webservice to do this in ISPyB:
> 
> https://github.com/ispyb/ISPyB/blob/master/ispyb-ws/src/main/java/ispyb/ws/soap/mx/ToolsForCollectionWebService.java#L1752
> 
> Mxcube needs to populate the start and end time then load times can be reported on

**Comment by IvarsKarpics** [comment]
Hi,

The code that stores robot action in ispyb is in the queue_entry: https://github.com/mxcube/HardwareRepository/blob/c2beedabe5f7b4f47b67665f5953e52bef1b8be8/HardwareObjects/queue_entry.py#L1687
https://github.com/mxcube/HardwareRepository/blob/c2beedabe5f7b4f47b67665f5953e52bef1b8be8/HardwareObjects/queue_entry.py#L1740-L1747
In the Qt version the method is called when a sample is mounted from the sample tree. I am not sure how in mxcube3 the sample mounting is handled.

**Comment by marcus-oscarsson** [comment]
I see, we are using an alternative mount_sample method that are slightly different from this one. The code in queue_entry is otherwise the same between the two versions. I recall that we've had some discussion regarding the load times before so I have to see with the others what we have said as well. We have also said that we wanted to use the mount_sample more or less as it is in queue_entry so I will take a look at the robot action part when we look at that.

**Comment by marcus-oscarsson** [comment]
Done
