### ISSUE TITLE
Python2 and 3 compatability

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/HardwareRepository#468]
Current syntax is not supported in python2:

https://github.com/mxcube/HardwareRepository/blob/1f131a78c4c940ffab6a4dbfc1bea9fdc8dc86ff/Command/embl/StandardClient.py#L270

Some time ago we agreed to keep both python2 and python3 compatability.

**Comment by marcus-oscarsson** [comment]
This seems to be solved, please reopen if you find another instance from raise from. A quick grep did not result in anything.
