### ISSUE TITLE
wait_ready / is_ready

### ISSUE THREAD

**Issue by rhfogh** [mxcube/HardwareRepository#475]
HardwareObjects should in principle use the is_ready / wait_ready implemented in superclasses (HardwareObhjectMixin, to be precise) to avoid duplication - unless of course there are specific needs  The superclass functions essentially track the state, so that any time the state changes to READY the object becomes ready, and relies on the underlying hardware changing state to READY (as it surely ought). 

The situation is too complex for third parties (like me) to barge into, but I think another look at wait functions is warranted, particularly for GenericDiffractometer and its subclasses, BlissEnergy, ExporterMotor and subclasses, and MD2Motor and subclasses. Possibly, wait_end_of_move, and waitEndOfMove are no longer necessary??

**Comment by marcus-oscarsson** [comment]
Closing this one
