### ISSUE TITLE
Add licence and attributes as header to all code files

### ISSUE THREAD

**Issue by jordiandreu** [mxcube/HardwareRepository#511]
This is a two-fold issue:
* Decide on the licence text to use as header on the code files.
* Decided the list of attributes to use: __copyright__, etc...

**Comment by jordiandreu** [comment]
This is the current licence text I could found in some code:

```
> #
> #  Project: MXCuBE
> #  https://github.com/mxcube.
> #
> #  This file is part of MXCuBE software.
> #
> #  MXCuBE is free software: you can redistribute it and/or modify
> #  it under the terms of the GNU Lesser General Public License as published by
> #  the Free Software Foundation, either version 3 of the License, or
> #  (at your option) any later version.
> #
> #  MXCuBE is distributed in the hope that it will be useful,
> #  but WITHOUT ANY WARRANTY; without even the implied warranty of
> #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
> #  GNU Lesser General Public License for more details.
> #
> #  You should have received a copy of the GNU Lesser General Public License
> #  along with MXCuBE.  If not, see <http://www.gnu.org/licenses/>.a
```

**Comment by jordiandreu** [comment]
These are some of the attributes I have collected:

> __credits__ = ["The MxCuBE collaboration"]
> __copyright__ = """ Copyright 2019 by the MXCuBE collaboration """
> __license__ = "LGPLv3+"
> __version__ = "2.3."
> __api__ = "3"
> __category__ = "Actuator"

**Comment by rhfogh** [comment]
My default header text is below, just for inspiration. I can modify it easily:

#! /usr/bin/env python
# encoding: utf-8
# 
# This file is part of MXCuBE.
# 
# MXCuBE is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# MXCuBE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with MXCuBE.  If not, see <https://www.gnu.org/licenses/>.
"""
"""

from __future__ import division, absolute_import
from __future__ import print_function, unicode_literals

__copyright__ = """ Copyright © 2016 - 2020 by MXCuBE Collaboration """
__license__ = "LGPLv3+"
__author__ = "rhfogh"
__date__ = "02/04/2020"

**Comment by IvarsKarpics** [comment]
* I think pylint had problem with that copyright symbol. I would remove it. 
* Not sure if we have to put __author__ It is difficult to say who is the actual author and/or where 
* I would keep the Project: MXCuBE and the link to the project

**Comment by rhfogh** [comment]
@IvarsKarpics 
I agree with you. I was not putting my version up as a proposal, just for inspiration.
Maybe someone should eventually make a PR, initially for just a few files, that we could then review and approve??

**Comment by jordiandreu** [comment]
> * I think pylint had problem with that copyright symbol. I would remove it.
Indeed, please.
> * Not sure if we have to put **author** It is difficult to say who is the actual author and/or where
I agree, maybe is not appropiate.
> * I would keep the Project: MXCuBE and the link to the project

@rhfogh what should date be? creation? last revision (it could be hard to maintain?)

**Comment by rhfogh** [comment]
These tags do not seem to be particularly standardised, except for \_\_version\_\_. So we should choose for ourselves what we think is a good description. I think we should start with @jordiandreu 's tags , and review those (I only gave my version because I thought we were still just gathering inspiration. Sorry for the confusion.). 

So, getting down to brass tacks, I have nothing to either add or subtract from Jordi's set of tags.

A few comments:

 -  \_\_copyright\_\_: I have more often seen a range of dates (start date to current date) as opposed to a single year, e.g. 
\_\_copyright\_\_ = """ Copyright © 2016 - 2020 by MXCuBE Collaboration """

 - \_\_version\_\_ We need some very precise agreements about hat we are versioning here. The file? The HardwareRepository? The mxcube repository? The release? The UI?

 - \_\_api\_\_ Maybe a word as opposed to a number. Is thi  the Qt v. web distinction? Or what are we versioning hers?


In case you still care about your specific questions:

 - From my experience pylint has no problems with the copyright symbol, but then I put 
         # encoding: utf-8
  at the top of the file. 

 - As for \_\_date\_\_ , my editor puts in the file creation date for me, after which it stays unchanged.

**Comment by marcus-oscarsson** [comment]
Hey,

I also prefer to remove author and simply let __copyright__ = """ Copyright © 2016 - 2020 by MXCuBE Collaboration """ indicate that its part of the MXCuBE project.

git can be used to get both author and date information so I don't think we need to keep those in the files.

__version__ and __api__ seems to be complicated to have on file level so I would prefer if we removed those

**Comment by marcus-oscarsson** [comment]
So for me it would be sufficient with

`
#! /usr/bin/env python
# encoding: utf-8
#
# This file is part of MXCuBE.
.
. ( I think GPL requires the short preamble version in each file, right ?)
.
__copyright__ = """ Copyright © 2016 - 2020 by MXCuBE Collaboration """
__license__ = "LGPLv3+"
`

And we should maybe change the starting date to date back a few more years ?

**Comment by rhfogh** [comment]
@marcus-oscarsson  Sounds fine to me.

**Comment by beteva** [comment]
For the text at the beginning I would let @rhfogh see what is relevant.. Otherwise agree with @marcus-oscarsson to have only the `__copyrght__` and the `__license__` statements. As it comes fro the years, I would suggest the start to be 2010, as this is the year of the first paper about MxCUBE.

**Comment by jordiandreu** [comment]
> So for me it would be sufficient with
> 
> ```
> #! /usr/bin/env python
> # encoding: utf-8
> #
> # This file is part of MXCuBE.
> .
> . ( I think GPL requires the short preamble version in each file, right ?)
> .
> __copyright__ = """ Copyright © 2016 - 2020 by MXCuBE Collaboration """
> __license__ = "LGPLv3+"
> ```
> 
> And we should maybe change the starting date to date back a few more years ?

Yes, I think we need to add the short preamble to each file.
Agree also on changing the starting date.

**Comment by marcus-oscarsson** [comment]
Hello all,

Are everybody okey with this:

#! /usr/bin/env python  
# encoding: utf-8
#
# This file is part of MXCuBE.
.
. (GPL short preamble )
.
__copyright__ = """ Copyright © 2016 - 2020 by MXCuBE Collaboration """
__license__ = "LGPLv3+"

How about removing 
    #! /usr/bin/env python  

I dont think its needed unless we intend to run the file as a script right ?

If everybody is fine with the header above Ill add a template to the root of the repo

**Comment by beteva** [comment]
OK to remove 
#! /usr/bin/env python
