### ISSUE TITLE
Consider renaming def.update_values to def.emit_values

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/HardwareRepository#515]
Possible names:
* def.reemit_values, def.reemit_state
* def.refresh_values, def.refresh_state

**Comment by rhfogh** [comment]
reemit_values and refresh_values are fine.
I am not sure about reemit_/refresh _state.
The state function is actually used to update the internal _state attribute, which makes update better (and reemit clearly worse) IMHO.

**Comment by IvarsKarpics** [comment]
`self.emit_values()`

**Comment by marcus-oscarsson** [comment]
Solved
