### ISSUE TITLE
Order of enumeration members

### ISSUE THREAD

**Issue by rhfogh** [mxcube/HardwareRepository#524]
@marcus-oscarsson @beteva 
Looking in more detail, I realise that there is a slight problem with the ordering of enumeration members.

In python 3 they are ordered by specification order, both for list(MyEnum) and for MyEnum.\_\_members\_\_

But for Python 2 they are instead ordered by member.value, or by member.key if the values give an error. So getting the 'first' member in Python 2 will give you the member with the lowest value.

I am not sure if this will be a problem, and anyway it will disappear when we move to Python 3, but meanwhile, what do you think?

BTW, looking at the documentation, I notice that you can get a member both by

MyEnum.aname
and
MyEnum["aname"}

**Comment by beteva** [comment]
@rhfogh, thanks for pointing this out. I do not think there will be a problem, though, as we do not access the Enums by order. The only access which depends on the order is, when the value is a tuple, but there is no difference between python 2.7 and 3.7 on this level. Please, correct me if I am wrong.

**Comment by rhfogh** [comment]
@beteva 
There may be just one case (which I sort of vaguely remembered):
In MicroDiffZoomMockup.init() we have 
self.update_value(list(self.VALUES)[0])
I do not know if it is important which of the values we get, or if any will do. Also, looking at AbstractNState.initialise_values, it could be that the values are not given in any particular order (they are input via a dictionary), which would render the point moot. Anyway, if you do not think this is a potential problem we ought be able to let it lie.

How do you order the values in e.g. a zoom, BTW, for presentation to the user interface? Do you sort them by element.value?

Quite likely this is nothing, but since I was the one to propose the list(Enum) syntax, I just wanted to be sure that there was not a bug in there somewhere.

**Comment by beteva** [comment]
The MicrodiffZoom(inheriting ExporterNState)  ValueEnum is constructed from a dictionary like this:
{'LEVEL1': 1, 'LEVEL2': 2, 'LEVEL3': 3, 'LEVEL4': 4, 'LEVEL5': 5...}. In the GUI (mxcube3) it is a slider with min/max values given by get_limits (hence the utility of the function even for NState). The value sent is an integer, which is converted with the value_to_enum method, so no Enum indexes used. I will change MicroDiffZoomMockup accordingly.

**Comment by rhfogh** [comment]
Looks like this is not after all a problem
