### ISSUE TITLE
Replace codacy with something else

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/HardwareRepository#525]
I would like to raise question if we should replace codacy with something else (see discussion here: https://github.com/mxcube/mxcube/issues/345).
Option could be: https://www.sonarqube.org/
Do you have some other suggestions.

**Comment by IvarsKarpics** [comment]
I disabled codacy and now it is not required to merge a PR. Apparently there is an issue regarding github check runs api and endpoints. More info https://github.com/travis-ci/travis-ci/issues/10187#issuecomment-427471218 and here https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories
I will have a look at this

**Comment by rhfogh** [comment]
According to my code camp notes, @IvarsKarpics  had looked and not found anything better, and it was agreed to keep what we have, as the least troublesome option.

Can we close the issue now, or is tehre more?

**Comment by marcus-oscarsson** [comment]
You are right I think it can be closed ...

**Comment by rhfogh** [comment]
The issue has been examined (thanks @IvarsKarpics ). The April Code camp agreed to stick with the current solution
