### ISSUE TITLE
HardwareObject Specific state

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/HardwareRepository#542]
Dicussion started in #540 regarding specific state handling triggered the ideas (by @rhfogh):

1. Change return type of AbstractActuator.get_specific_state to 'Any' or if possible a more restrictive type i.e. Enum

2. removing AbstractActuator.update_specific_state and the specificStateChanged signal. I put them in AbstractActuator to treat specific states the same way as normal states

**Comment by marcus-oscarsson** [comment]
@rhfogh when you say the same way as specific state, what do you mean exactly that they will be emitted in the same signal state_changed ?

**Comment by rhfogh** [comment]
@marcus-oscarsson 
Originally I coded the two exactly parallel. Separate functions and separate signals for the two kinds of state. But I never understood particularly well how the specific states were supposed to work, so it is good we are getting that settled now.

For HardwareObjectStates we have update_state that (apart from managing the ready_event) emits <"stateChanged", (new_state)>.

The question is what we need for specific_state. One possibility is to have an update_specific_state that emits a separate signal 
<"specificStateChanged", (new_specific_state,)>
Another is to make do with emitting <"stateChanged", (new_state)>. and call get_specific_state as needed. 
A third (which I would really like to avoid) is to emit instead <"stateChanged" (new_state, new_specific_state)>; my gut feeling is that it is better not to mix the (optional and varied) specific states in with the handling of the (uniform and reliable) hardware states. 

It all depends on where the new value of the specific state is needed, and how you can get hold of it. This is a matter for those who understand how the hardware and the specific states should work.
