### ISSUE TITLE
AbstractFlux

### ISSUE THREAD

**Issue by beteva** [mxcube/HardwareRepository#572]
Discussion about how to implement the dose rate

**Comment by beteva** [comment]
Comment from @bourenkov:
The interpolation table dose_rate_per_photon_per_mmsq was created using "Absorbed dose calculations for macromolecular crystals: improvements to RADDOSE"
Paithankar, K.S., Owen, R.L and Garman, E.F J. Syn. Rad. (2009), 16, 152-162,
for some sensible crystal composition - I no longer remember which one exactly. Can easily be re-done if necessary.

To me the table is abstract enough to be here.

But except for P14 under certain conditions I would not know an instrument where the AbstractFlux.get_dose_rate() would be valid. Likewise, the AbstractBeam.evaluate_beam_info() method.

**Comment by beteva** [comment]
Thanks @bourenkov for the explanation.
As for the rest, this PR is only flux calculations for ID30B at ESRF. We need that somebody (probably @IvarsKarpics or you) have a closer look at AbstractFlux.

**Comment by beteva** [comment]
Comment from @rhfogh:
@bourenkov
True, the dose rate function assumes that the flux density can be calculated as the flux value divided by the rectangular beam area. And also that this average flux density is what actually bathes the crystal, which might not be the case in general. Either of which is probably true only for a well-adjusted top-hat beam. But then in more complex cases you would probably need to consider both the actual flux profile and the size and shape of the crystal to get a precise result. Maybe there are better, but still practicable ways of doing this. But would it not be useful to have a formula like this at least as an approximation, instead of simply having no information available at all?

Yes, @IvarsKarpics, your input would be very useful.

I should add our use case:
We are trying to have our workflow set a recommended transmission, which requires calculating the dose rate. If there is no MXCuBE function for calculating dose rate we would simply put the same function as part of the GPhL workflow, on the basis that an approximate calculation can still give better transmission settings than leaving it to the user to set by hand. But it is likely that having the function as part of the main MXCuBE might lead to more reliable estimates, at least on some beamlines.

**Comment by bourenkov** [comment]
@rhfogh 
a potential issue that I see is only with placing get_dose_rate() into an AbstractFlux, as the context in which the approximation is applicable remains essentially undefined. This would not be an issue if the method is kept in the GPhL workflow - where we are confident it is both useful and sufficient.

The  dose_rate_per_photon_per_mmsq(), in opposite, is valid in a rather general context, though a label pointing to 'average protein crystal composition' could still be useful.

**Comment by rhfogh** [comment]
@bourenkov 
Yes, that sounds rather sensible. Would it be possible to have a flux_density, defined as either average or peak, in the AbstractFlux, or is that also too ill-defined? I can see it might have problems, but on the other hand the people at the only ones who have any chance of making even a decent approximation to calculating it.

**Comment by rhfogh** [comment]
Following this discussion (which needs to be settled), the best solution seems to be putting a function dose_rate_per_photon_per_mmsq(energy) into AbstractFlux. People who need it (like me) can then claculate their own flux density to convert this into a dose rate.

QUESTION:
Does anyone use elliptical (i.e. not rectangular) beam descriptions?
Is there a more reliable way of getting teh beam area than simply the product of the x and y width?

**Comment by bourenkov** [comment]
Hi Rasmus, 

> On 5. Aug 2020, at 11:47, Rasmus H. Fogh <notifications@github.com> wrote:
> 
> 
> Following this discussion (which needs to be settled), the best solution seems to be putting a function dose_rate_per_photon_per_mmsq(energy) into AbstractFlux. People who need it (like me) can then claculate their own flux density to convert this into a dose rate.
> 
> QUESTION:
> Does anyone use elliptical (i.e. not rectangular) beam descriptions?
> 
- elliptical top-hat beams do not exist. Beams that are anisotropic bell-shape do look elliptical ( in some representations). Literally, an “area" of a “bell” would be nuisance - agreeably, I hope. 
> Is there a more reliable way of getting teh beam area than simply the product of the x and y width
> 
- It may be worth looking at the definition of diffraction weighted dose, which is now a standard normaliser for the beam shape effects. In certain approximations (e.g. for low dose, static large crystal etc.) one can define a norm of a bell-shaped beam, expressed in units of area, such that DWD is proportional to integral flux divided by that characteristic area over a good range of beam and crystal dimensions. 
But, you may also see that various - even quite wild - assumptions on beam/crystal shapes will lead to a DWD deviation of above by no more than a factor of two. 

I.e., in a sensible experiment difference in dose estimate by a factor 4/Pi (rectangle over ellipse area) is unlikely to produce any measurable difference.

Cheers
Gleb

**Comment by marcus-oscarsson** [comment]
Discussed during October code camp the 13th.

There is general interest in this kind of functionality and @rhfogh has already started some work on this that could be of general interest.

**Comment by beteva** [comment]
@rhfogh does #593 close this issue?

**Comment by rhfogh** [comment]
Yes it does. I am closing this issue.
