### ISSUE TITLE
Next MXCuBE (virtual) meeting at ALBA - developers session

### ISSUE THREAD

**Issue by jordiandreu** [mxcube/HardwareRepository#574]
Dear @all,

XALOC scientist are scheduling the next MXCuBE meeting (virtual) at ALBA, which will be held on 29th June, from 12:00 to 18:00 (tentative). The idea behind it is to cope with a suitable times for people from both China and Brazil.

Due to this tight schedule and the virtualization of the event due to the COVID-19, we would propose to do not schedule any specific developers or code-camp session this time during the meeting.

Nevertheless, we propose to keep working as we have been doing last months and maybe it may have sense to schedule a developers meeting (or code camp if necessary) previous to the ALBA meeting.

What are your thoughts about?

**Comment by laispc** [comment]
Hi @jordiandreu ! I think ALBA Meeting is too close for another code camp, but a quick dev meeting, with a simple agenda, could be okay.

**Comment by marcus-oscarsson** [comment]
Dear @ALL, @laispc and @jordiandreu 

First of all sorry for the late reply and thanks for asking and take care of this !

We have had a very tight schedule here at ESRF and we've had difficulties to find the time to organize something earlier this month. I think I'ts now, unfortunately, a little bit tight with a developers meeting just before the ALBA meeting.

The impression I got is that this meeting will be a lighter version of the meeting considering the circumstances, thus leaving out the code camp on the actual meeting is more or less expected. (In my opinion).

I suggest that we keep it simple by having a our monthly developers meeting as we would have during June in anyways. We will circulate a preliminary agenda before the meeting as usually 

What was the time slot / duration for the developers session again ?

All the best,
Marcus
