### ISSUE TITLE
Bad function names 'connected/disconnected'

### ISSUE THREAD

**Issue by rhfogh** [mxcube/HardwareRepository#579]
Proposal for refactoring:

There seems to be a fairly wide usage of have 'connected() / disconnected()' as functions that **set** values. This is confusing, the most natural interpretation of those names  is that they should *return* a value.

I would propose getting rid of 'connected/disconnected' altogether, use  'connect/disconnect' to set values, and 'is_connected' to get them.

**Comment by IvarsKarpics** [comment]
Sounds good to me. Maybe we can implement this after we complete CamelCase to snake_case conversion?

**Comment by rhfogh** [comment]
@IvarsKarpics 
I'd agree. We certainly need to get the snake case sorted first.

**Comment by marcus-oscarsson** [comment]
Duplication #589
