### ISSUE TITLE
Allowed Transmission values

### ISSUE THREAD

**Issue by rhfogh** [mxcube/HardwareRepository#580]
Is there a way of getting the list of possible transmission values for the case where the transmission is not continuously variable? If it cannot be done in code, could we add it? Or, maybe simpler, could people tell what set of transmission values are currently allowed?

We are looking at the granularity of possible transmission values, especially at low transmission, to see if we need to take it into account when setting transmission for strategies.

**Comment by beteva** [comment]
At ESRF the transmission for a tunable beamline is calculated as a linear interpolation between two close energies for which we have the transmission vales for each filter. The filters can be up to 12, so getting a list is rather difficult, if not impossible.  If you want to get a list, it will be a rather long one and on top of it it will change for each energy. What you can have is the access to the calculations and the file where we have the transmission for each filer.
