### ISSUE TITLE
Limit handling for AbstractNState

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/HardwareRepository#587]
This topic was already discussed in detail during the code camp in [April](https://mxcube.github.io/mxcube/doc/developers_meetings/MinutesGrenoble20200402Virtual.pdf) and the current solution was put in place.

The principle question discussed where whether "n-state" objects have limits and how to handle them, resulting in the decision that they might in some rare cases have limits but there is no default implementation for handling those provided by AbstractNState. 

A bug in re_emit_values of AbstractNState incorrectly calling re_emit_values of AbstractActatutor (that does have limit handling) raised an exception.

The bug is fixed by #586 but this issue is created to discuss any remaining questions and perhaps draft another solution if necessary.

**Comment by rhfogh** [comment]
In line with Vicente's original PR, I think that we should implement validate_value in AbstractActuator, using (I'd  say) a copy of AbstractMotor.validate_value. The alternative implementation in AbstractActuator will overide the implementaiton in teh superclass, and should give the fight behaviour everywhere. If we want diferent behavious in special cases we can always override.

The reasons are those that VIcente mentioned: avoiding duplication and having the validation implkementatoin close to where limits are introduced
