### ISSUE TITLE
Python package name ideas

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/HardwareRepository#604]
Name suggestions for the new Python package as discussed during the last developers meeting.

The names that were mentioned during the meeting:

- mxcube_core
- mx3core
- mxcube_hwr
- mx3hwr

Marcus

**Comment by marcus-oscarsson** [comment]
The deadline is  the 8th of January so we will chose the most popular name at that date :)

**Comment by IvarsKarpics** [comment]
I am voting for mxcube_core. Please no version number in the package name.

**Comment by rhfogh** [comment]
I can live with all of them, but something without the underscore would be better.

mxcore? mxccore?

Or you could argue that the '3' stood for 'cube' - after all the official logo says 'mx3' (superscript 3), on top of a histidine.

**Comment by beteva** [comment]
I vote for mx3core, where 3 stands for cube, not for a version (just before the deadline :smiley: )

**Comment by hellmig** [comment]
One vote for mx3core from my side, also seeing the mx3 as an abbreviation for mxcube.

**Comment by marcus-oscarsson** [comment]
Hm, not easy this. I guess it's nice if we can avoid the underscore as it makes it easier to type when we import. One can of course argue if it's easier to write (or more readable to use the number 3) ?

I guess whatever logic we chose should also be applicable to the frontends at some stage, i.e mx3web mx3qt alternately mxcube_web or mxcube_qt.

Thinking about it and test typing it to get a feeling for the name :) I vote for **mxcubecore** all in one word :)

**Comment by rhfogh** [comment]
@marcus-oscarsson 
mxcubecore is good, no numbers to misunderstand/argue about, no underscores, and not *too* long. I can live with all of them, but I am certainly happy with mxcubecore.

**Comment by IvarsKarpics** [comment]
I vote for mxcubecore, mxcubeweb and mxcubeqt. It keeps the mxcube name, there is no underscore or number.

**Comment by beteva** [comment]
mxcubecore, mxcubeweb and mxcubeqt is fine for me as well.

**Comment by jordiandreu** [comment]
Fine as well for me, like the idea to maintain the 'cube' string.

**Comment by marcus-oscarsson** [comment]
So it looks like mxcubecore is the most popular compromise :) then, at least from what I can see ?. What about going over it one last time during next meeting and then update #605 ?

**Comment by marcus-oscarsson** [comment]
So we decided for mxcubecore !
