### ISSUE TITLE
Cannot find  SpecConnectionsManager 

### ISSUE THREAD

**Issue by laoniu2020** [mxcube/HardwareRepository#609]
I search files in HardwareRepository and Mxcube3 project, but cannot find SpecConnectionsManager definition.

**Comment by txolutions** [comment]
There is an extra module "specclient" that you may need to download and install but it should be necessary. 

http://github.com/mxcube/specclient/

**Comment by laoniu2020** [comment]
Thank you very much. 
I notice this moudle not in the requirements_python3..txt. I will install manually.
