### ISSUE TITLE
BaseHardwareObjects: Objects exposing internal data structures

### ISSUE THREAD

**Issue by rhfogh** [mxcube/HardwareRepository#82]
I got bitten by a lack of encapsulation in HardwareObjectNode
The HardwareObjectNode.getProperties function returns the actual, internal dictionary, so that modifying the result of the  function call means you are modifying the object. This was unexpected  and, I would say, fragile. Normally you would expect that the result of a function call could be modified without modifying the original object (encapsulation). So:

- Is this a bug or a feature? 
- What is the MXCuBE policy on encapsulation? For function results? for attributes? for _attributes?
- Is there code that depends on this behaviour?
- Can or should I fix this and add encapsulation, either here, or globally?

**Comment by IvarsKarpics** [comment]
Hi @rhfogh ,

I would say this is an issue (topic) that needs a continues work. Method like `getProperties` should not return internal objects, so my answer is: this is a bug.
Thank you bringing this up and you are welcomed to start improving this. A PR would be highly appreciated!

**Comment by mguijarr** [comment]
Python dictionaries are handled "by reference". So every time a dictionary is returned (or a list, for example - this is true for all mutable objects), the return value is really the object, not a copy.

As far as I understand you modified (by mistake ?) the values returned by a 'getProperties' call that returned a dictionary - indeed, we can expect the framework to be more 'protective' and to not expose objects knowing they can be modified by framework users. Returning a copy (beware: a deep copy !) would make the framework more robust.

So:
* it's more a bug than a feature
* encapsulation rules in MXCuBE are the same as in Python, it is left to the good collaboration of programmers vs users
* I don't think code depends on this behaviour
* A pull request is welcome to fix the problem

Thanks !

**Comment by rhfogh** [comment]
Not sure I agree with this fix - and I am starting to look at an alternative pull request myself. Anyway:

For one thing, you should be returning a copy, as you say.

But more fundamentally, I do not think __attributes are the solution here. The '__' is only really needed to prevent an attribute from being referenced in subclasses, and should, I think, be limited to this case. For normal internal attributes a single underscore prefix should be enough (e.g. '_attribute') to signal that this is an internal attribute.  Python programmers are supposed to be grown-up enough to avoid doing the wrong thing, even if there is no one around to say 'stop'. I would propose this kind of hierarchy:

- function access ( e.g. obj.get_xyz(), obj.set_xyz(value)): Mutable collections and maps must be copied both on setting and getting so you are safe from inadvertently modifying object internals. Mutable objects should be returned as they are (e.g. obj.get_diffractometer_hwobj())

- Internal attribute access (e.g. obj._xyz): Returns the internal attribute (NOT as copy), and modifying it WILL modify the object. It is up to programmers to leave internal attributes alone - or deal with the consequences.

- Non-inherited attribute(e.g. obj.__xyz): Reserved for attributes that must be shielded from access from subclasses. 

- That leaves plain attributes (e.g. obj.xyz): Here one question is whether we should simply discourage them and recommend get_ and set_ methods instead? I gather that people prefer function access to properties (regrettably ;-) ), and it is not smart to have to change from attribute to function access if you have to add constraint checking or something. To the extent we do use them, attributes that are immutable values (floats, strings, tuples, frozensets, ...) are not a problem, and attributes that are plain objects (e.g. obj.centred_position) should return the object held internally, just like function calls. In the absence of properties, I guess that obj.a_list should return the internal list (and programmer beware), but it would really be better not to have such attributes.

**Comment by rhfogh** [comment]
This should still be kept in mind, but it hardly qualifies as a open issue after over a year.
